### ISSUE TITLE
Doorbell reboot?

### ISSUE THREAD

**Issue by jlg89** [hufftheweevil/august-connect#2]
The August Doorbell Cam needs rebooting on a regular basis, and it's do-able in the app by drilling down into the doorbell prefs and selecting "reboot doorbell." If it were possible to add this into the code, we could create a simple switch in HomeKit to trigger a doorbell reboot.

**Comment by hufftheweevil** [comment]
Do you know the endpoint for that? I don't have a doorbell cam, so I can't do much investigating/testing.

**Comment by jlg89** [comment]
Not sure what the endpoint is, I guess we'd need to Wireshark it.

**Comment by jlg89** [comment]
I realize it's not as simple as Wireshark, since everything is encrypted. If I send you a Doorbell Cam, would you have the time & desire to work out that endpoint? It would actually be super useful to have the endpoints for both sending a doorbell reboot, and receiving a doorbell button press.

**Comment by hufftheweevil** [comment]
Sorry, but I'm not even sure where to start, even if I had one of them. I'm not well versed in reverse engineering that kind of stuff. The only reason I have the endpoints that I do is from others on the internet who found them before me.
