### ISSUE TITLE
Yale Home

### ISSUE THREAD

**Issue by donavanbecker** [hufftheweevil/august-connect#4]
Hey @hufftheweevil,

Looks like Yale has changed somethings for non-us users. Looks like there is a fix here in an issue of another one of your repos. I was able to fork your package and change this to see if it would work and it does, somewhat.

Issue with Fix discussed:
https://github.com/hufftheweevil/node-red-contrib-august/issues/3

Any chance we could introduce `countryCode` into the config and use different `DEFAULT_PN_SUB_KEY`, `DEFAULT_API_KEY`, and `API_URL` for any `countryCode` that is not `US`?

**Comment by hufftheweevil** [comment]
@donavanbecker Thank you for the PR! I simplified a few lines of code and also added to the docs.

Fixed with https://github.com/hufftheweevil/august-api/commit/107512b9e3baa336ed6ee7c03b5290259b0f1657

**Comment by donavanbecker** [comment]
No problem, there might be more changes that need to be made, but from what I have seen this has allowed the connect to happen.

**Comment by henrikekblad** [comment]
@donavanbecker How/where did you find the key? It looks like they might have changed it again for none-US users.
