### ISSUE TITLE
FetchError: Status 401 (undefined): undefined

### ISSUE THREAD

**Issue by donavanbecker** [hufftheweevil/august-connect#6]
```
FetchError: Status 401 (undefined): undefined

/homebridge/node_modules/homebridge-august/node_modules/august-api/src/methods/details.js:9
    let locks = Object.keys(await this._locks())
```

config sending:
```
"augustId": "email@email.com",
"password": "**************",
"installId": "********-****-****-****-************",
"isValidated": true,
```

**Comment by donavanbecker** [comment]
@hufftheweevil, not sure what is going on but getting this on restart of the homebridge plugin. I am able to get the api to connect on first run, then on restart users are getting this. [homebridge-august#75](https://github.com/donavanbecker/homebridge-august/issues/75)

**Comment by hufftheweevil** [comment]
It's possible that some of the endpoints are different for the other API.

I'm actually having some new difficulties myself with the US API.

It's unfortunate that August doesn't want to make this more accessible. I get the security concerns, but there are smart ways to handle that.

**Comment by donavanbecker** [comment]
I am using the US API also, so I think it is across the board.

**Comment by donavanbecker** [comment]
Wonder if we can find something here: [yalexs](https://github.com/bdraco/yalexs)?
